// Code generated by MockGen. DO NOT EDIT.
// Source: proxy/services/disco.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	go_ipfs_api "github.com/ipfs/go-ipfs-api"
)

// MockIPFSClient is a mock of IPFSClient interface.
type MockIPFSClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPFSClientMockRecorder
}

// MockIPFSClientMockRecorder is the mock recorder for MockIPFSClient.
type MockIPFSClientMockRecorder struct {
	mock *MockIPFSClient
}

// NewMockIPFSClient creates a new mock instance.
func NewMockIPFSClient(ctrl *gomock.Controller) *MockIPFSClient {
	mock := &MockIPFSClient{ctrl: ctrl}
	mock.recorder = &MockIPFSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPFSClient) EXPECT() *MockIPFSClientMockRecorder {
	return m.recorder
}

// FilesCp mocks base method.
func (m *MockIPFSClient) FilesCp(ctx context.Context, src, dest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesCp", ctx, src, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilesCp indicates an expected call of FilesCp.
func (mr *MockIPFSClientMockRecorder) FilesCp(ctx, src, dest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesCp", reflect.TypeOf((*MockIPFSClient)(nil).FilesCp), ctx, src, dest)
}

// FilesMkdir mocks base method.
func (m *MockIPFSClient) FilesMkdir(ctx context.Context, path string, options ...go_ipfs_api.FilesOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, path}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilesMkdir", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilesMkdir indicates an expected call of FilesMkdir.
func (mr *MockIPFSClientMockRecorder) FilesMkdir(ctx, path interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, path}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesMkdir", reflect.TypeOf((*MockIPFSClient)(nil).FilesMkdir), varargs...)
}

// FilesRead mocks base method.
func (m *MockIPFSClient) FilesRead(ctx context.Context, path string, options ...go_ipfs_api.FilesOpt) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, path}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilesRead", varargs...)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesRead indicates an expected call of FilesRead.
func (mr *MockIPFSClientMockRecorder) FilesRead(ctx, path interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, path}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesRead", reflect.TypeOf((*MockIPFSClient)(nil).FilesRead), varargs...)
}

// FilesRm mocks base method.
func (m *MockIPFSClient) FilesRm(ctx context.Context, path string, force bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilesRm", ctx, path, force)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilesRm indicates an expected call of FilesRm.
func (mr *MockIPFSClientMockRecorder) FilesRm(ctx, path, force interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesRm", reflect.TypeOf((*MockIPFSClient)(nil).FilesRm), ctx, path, force)
}

// FilesStat mocks base method.
func (m *MockIPFSClient) FilesStat(ctx context.Context, path string, options ...go_ipfs_api.FilesOpt) (*go_ipfs_api.FilesStatObject, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, path}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilesStat", varargs...)
	ret0, _ := ret[0].(*go_ipfs_api.FilesStatObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilesStat indicates an expected call of FilesStat.
func (mr *MockIPFSClientMockRecorder) FilesStat(ctx, path interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, path}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesStat", reflect.TypeOf((*MockIPFSClient)(nil).FilesStat), varargs...)
}

// FilesWrite mocks base method.
func (m *MockIPFSClient) FilesWrite(ctx context.Context, path string, data io.Reader, options ...go_ipfs_api.FilesOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, path, data}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilesWrite", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// FilesWrite indicates an expected call of FilesWrite.
func (mr *MockIPFSClientMockRecorder) FilesWrite(ctx, path, data interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, path, data}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilesWrite", reflect.TypeOf((*MockIPFSClient)(nil).FilesWrite), varargs...)
}
